import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = window.PINKCHAT_CONFIG || {};
const $ = s => document.querySelector(s);
const state = { supabase:null, user:null, profile:null, chats:[], active:null, messages:[], channel:null, photo:null };
const els = {app:$('#app'),chatList:$('#chatList'),messages:$('#messages'),form:$('#messageForm'),input:$('#messageInput'),modal:$('#modal'),modalContent:$('#modalContent'),toast:$('#toast'),photoInput:$('#photoInput'),photoPreview:$('#photoPreview'),photoPreviewImage:$('#photoPreviewImage'),photoPreviewSize:$('#photoPreviewSize'),stories:$('#stories')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('ru',{hour:'2-digit',minute:'2-digit'}).format(new Date(d));
const toast=t=>{els.toast.textContent=t;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2300)};
const openModal=html=>{els.modalContent.innerHTML=html;els.modal.showModal()};
const initials=n=>(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const configured=cfg.supabaseUrl?.includes('supabase.co') && cfg.supabaseAnonKey?.startsWith('sb_publishable_');
async function nameToEmail(name){const clean=name.trim().toLowerCase().replace(/\s+/g,' ');const bytes=new TextEncoder().encode(clean);const hash=await crypto.subtle.digest('SHA-256',bytes);const hex=[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');return `user-${hex.slice(0,32)}@pinkchat.local`}


function applyTheme(theme=localStorage.getItem('pinkchat-theme')||'pink'){document.documentElement.dataset.theme=theme;localStorage.setItem('pinkchat-theme',theme)}
function renderStories(){const stories=JSON.parse(localStorage.getItem('pinkchat-stories')||'[]').filter(x=>Date.now()-x.createdAt<86400000);localStorage.setItem('pinkchat-stories',JSON.stringify(stories));els.stories.innerHTML=`<button class="story add-story" id="addStory"><span class="story-avatar">＋</span><span>Твоя история</span></button>`+stories.map((s,i)=>`<button class="story" data-story="${i}"><span class="story-ring"><span class="story-avatar">${esc(initials(s.name))}</span></span><span>${esc(s.name)}</span></button>`).join('');$('#addStory').onclick=showAddStory;els.stories.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>showStory(stories[+b.dataset.story]));}
function showAddStory(){openModal('<h2>Новая история</h2><input id="storyFile" class="modal-input" type="file" accept="image/*"><input id="storyCaption" class="modal-input" placeholder="Подпись"><button id="storyPublish" class="primary-button" type="button">Опубликовать</button>');$('#storyPublish').onclick=()=>{const f=$('#storyFile').files[0];if(!f)return toast('Выбери фото');if(f.size>4_000_000)return toast('Фото слишком большое');const r=new FileReader();r.onload=()=>{const a=JSON.parse(localStorage.getItem('pinkchat-stories')||'[]');a.unshift({name:state.profile?.display_name||'Ты',image:r.result,caption:$('#storyCaption').value,createdAt:Date.now()});localStorage.setItem('pinkchat-stories',JSON.stringify(a.slice(0,10)));els.modal.close();renderStories()};r.readAsDataURL(f)}}
function showStory(s){$('#storyViewerContent').innerHTML=`<div class="story-media"><img src="${s.image}" alt="История"><div class="story-caption"><strong>${esc(s.name)}</strong><p>${esc(s.caption)}</p></div></div>`;$('#storyViewer').showModal()}

async function boot(){applyTheme();renderStories();if(!configured){openModal('<h2>Ошибка настройки</h2><p class="modal-lead">В config.js не указан Supabase.</p>');return}state.supabase=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await state.supabase.auth.getSession();if(!session)return showAuth();state.user=session.user;await loadProfile();await loadChats();state.supabase.auth.onAuthStateChange(async(_,s)=>{if(!s){state.user=null;showAuth()}})}
function showAuth(){openModal(`<div class="auth-logo">♥</div><h2>Добро пожаловать в PinkChat</h2><p class="modal-lead">Для входа нужны только имя и пароль</p><input id="authName" class="modal-input" autocomplete="username" placeholder="Твоё имя"><input id="authPass" class="modal-input" type="password" minlength="4" autocomplete="current-password" placeholder="Пароль — минимум 4 символа"><button id="signIn" class="primary-button" type="button">Войти</button><button id="signUp" class="modal-action" type="button">Создать аккаунт</button><p class="tiny-note">Имя должно быть уникальным. Запомни точное написание.</p>`);$('.modal-close').style.display='none';$('#signIn').onclick=()=>auth(false);$('#signUp').onclick=()=>auth(true)}
async function auth(signup){const password=$('#authPass').value,name=$('#authName').value.trim();if(name.length<2||password.length<4)return toast('Имя от 2 символов, пароль от 4');const email=await nameToEmail(name);const res=signup?await state.supabase.auth.signUp({email,password,options:{data:{display_name:name,login_name:name.toLowerCase()}}}):await state.supabase.auth.signInWithPassword({email,password});if(res.error){const msg=res.error.message.includes('already registered')?'Такое имя уже занято':res.error.message;return toast(msg)}if(signup&&!res.data.session)return toast('В Supabase выключи Confirm email');state.user=res.data.user;els.modal.close();$('.modal-close').style.display='';await loadProfile();await loadChats()}
async function loadProfile(){let {data}=await state.supabase.from('profiles').select('*').eq('id',state.user.id).single();state.profile=data||{display_name:state.user.user_metadata?.display_name||'Пользователь',bio:'',theme:'pink',is_admin:false};applyTheme(state.profile.theme||'pink')}
async function loadChats(){const {data,error}=await state.supabase.rpc('pinkchat_list_conversations');if(error)return toast(error.message);state.chats=data||[];renderChats();if(state.chats[0])openChat(state.chats[0].conversation_id)}
function renderChats(q=''){const rows=state.chats.filter(c=>(c.other_name||'').toLowerCase().includes(q.toLowerCase()));els.chatList.innerHTML=rows.length?rows.map(c=>`<button class="chat-item ${state.active===c.conversation_id?'active':''}" data-id="${c.conversation_id}"><span class="chat-avatar">${esc(initials(c.other_name))}</span><span class="chat-main"><span class="chat-name-row"><strong>${esc(c.other_name||c.other_email)}</strong><time>${c.last_message_at?fmt(c.last_message_at):''}</time></span><span class="chat-preview-row"><span class="chat-preview">${esc(c.last_message||'Начните общение')}</span>${c.unread_count?`<span class="unread">${c.unread_count}</span>`:''}</span></span></button>`).join(''):'<div class="empty-list">Чатов пока нет.<br>Нажми «＋», чтобы начать.</div>';els.chatList.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openChat(b.dataset.id));$('#totalUnread').textContent=(state.chats.reduce((a,c)=>a+Number(c.unread_count||0),0)||0)+' новых'}
async function openChat(id){state.active=id;renderChats($('#chatSearch').value);els.app.classList.add('chat-open');const c=state.chats.find(x=>x.conversation_id===id);$('#activeName').textContent=c?.other_name||'Чат';$('#activeAvatar').textContent=initials(c?.other_name);$('#activeStatus').textContent='в PinkChat';await state.supabase.rpc('pinkchat_mark_read',{target_conversation_id:id});const {data,error}=await state.supabase.from('messages').select('*').eq('conversation_id',id).order('created_at');if(error)return toast(error.message);state.messages=data||[];await hydrateImages();renderMessages();subscribe(id)}
async function hydrateImages(){for(const m of state.messages){if(m.image_path){const {data}=await state.supabase.storage.from('chat-media').createSignedUrl(m.image_path,3600);m.image_url=data?.signedUrl}}}
function renderMessages(){els.messages.innerHTML='<div class="day-divider">Сегодня</div>'+state.messages.map(m=>`<div class="message-row ${m.sender_id===state.user.id?'mine':'theirs'}"><div class="bubble" data-msg="${m.id}">${m.image_url?`<img class="message-photo" src="${m.image_url}" alt="Фото">`:''}${m.body?`<p>${esc(m.body)}</p>`:''}<div class="message-meta"><span>${m.edited_at?'изм. ':''}${fmt(m.created_at)}</span>${m.sender_id===state.user.id?'<span>✓✓</span>':''}</div></div></div>`).join('');els.messages.querySelectorAll(state.profile?.is_admin?'.bubble':'.mine .bubble').forEach(x=>{x.ondblclick=()=>messageMenu(x.dataset.msg);x.oncontextmenu=e=>{e.preventDefault();messageMenu(x.dataset.msg)}});els.messages.querySelectorAll('.message-photo').forEach(i=>i.onclick=()=>{openModal(`<img class="modal-image" src="${i.src}">`) });requestAnimationFrame(()=>els.messages.scrollTop=els.messages.scrollHeight)}
function subscribe(id){if(state.channel)state.supabase.removeChannel(state.channel);state.channel=state.supabase.channel('messages-'+id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},()=>openChat(id)).subscribe()}
async function sendMessage(e){e.preventDefault();const body=els.input.value.trim();if(!body&&!state.photo)return;let image_path=null;if(state.photo){const path=`${state.user.id}/${state.active}/${crypto.randomUUID()}.${state.photo.name.split('.').pop()||'jpg'}`;const up=await state.supabase.storage.from('chat-media').upload(path,state.photo,{contentType:state.photo.type,upsert:false});if(up.error)return toast(up.error.message);image_path=path}const {error}=await state.supabase.from('messages').insert({conversation_id:state.active,sender_id:state.user.id,body:body||null,image_path});if(error)return toast(error.message);clearComposer();await loadChats()}
function clearComposer(){els.input.value='';state.photo=null;els.photoInput.value='';els.photoPreview.classList.add('hidden')}
async function messageMenu(id){const m=state.messages.find(x=>x.id===id);openModal(`<h2>Сообщение</h2>${m.body?'<button id="editMessage" class="modal-action">✏️ Редактировать</button>':''}<button id="deleteMessage" class="modal-action danger">🗑 Удалить</button>`);if($('#editMessage'))$('#editMessage').onclick=async()=>{const body=prompt('Новый текст',m.body);if(body===null)return;const {error}=await state.supabase.from('messages').update({body:body.trim(),edited_at:new Date().toISOString()}).eq('id',id).eq('sender_id',state.user.id);if(error)return toast(error.message);els.modal.close();openChat(state.active)};$('#deleteMessage').onclick=async()=>{let q=state.supabase.from('messages').delete().eq('id',id);if(!state.profile?.is_admin)q=q.eq('sender_id',state.user.id);const {error}=await q;if(error)return toast(error.message);els.modal.close();openChat(state.active)}}
function newChat(){openModal('<h2>Новый чат</h2><p class="modal-lead">Введи точное имя зарегистрированного друга</p><input id="friendName" class="modal-input" placeholder="Например: Катя"><button id="createChat" class="primary-button" type="button">Начать переписку</button>');$('#createChat').onclick=async()=>{const {data,error}=await state.supabase.rpc('pinkchat_start_direct_chat_by_name',{target_name:$('#friendName').value.trim()});if(error)return toast(error.message);els.modal.close();await loadChats();openChat(data)}}
function profile(){openModal(`<h2>Профиль ${state.profile.is_admin?'👑':''}</h2><input id="pName" class="modal-input" value="${esc(state.profile.display_name||'')}" placeholder="Имя"><textarea id="pBio" class="modal-input" placeholder="О себе">${esc(state.profile.bio||'')}</textarea><select id="pTheme" class="modal-input"><option value="pink">Розовая</option><option value="purple">Фиолетовая</option><option value="peach">Персиковая</option><option value="dark">Тёмная</option></select><button id="saveProfile" class="primary-button" type="button">Сохранить</button>${state.profile.is_admin?'<button id="adminPanel" class="modal-action" type="button">👑 Админ-панель</button>':''}<button id="logout" class="modal-action danger" type="button">Выйти</button>`);$('#pTheme').value=state.profile.theme||'pink';$('#saveProfile').onclick=async()=>{const patch={display_name:$('#pName').value.trim(),bio:$('#pBio').value.trim(),theme:$('#pTheme').value};const {error}=await state.supabase.from('profiles').update(patch).eq('id',state.user.id);if(error)return toast(error.message);state.profile={...state.profile,...patch};applyTheme(patch.theme);els.modal.close();toast('Профиль сохранён')};if($('#adminPanel'))$('#adminPanel').onclick=adminPanel;$('#logout').onclick=()=>state.supabase.auth.signOut()}
async function adminPanel(){const [{data:users},{data:msgs}]=await Promise.all([state.supabase.from('profiles').select('id,display_name,bio,is_admin,created_at').order('created_at',{ascending:false}).limit(100),state.supabase.from('messages').select('id,body,created_at,sender_id').order('created_at',{ascending:false}).limit(30)]);openModal(`<h2>👑 Админ-панель</h2><p class="modal-lead">Пользователей: ${users?.length||0}</p><div class="admin-list">${(users||[]).map(u=>`<div class="admin-row"><span><strong>${esc(u.display_name)}</strong><small>${u.is_admin?'Администратор':'Пользователь'}</small></span></div>`).join('')}</div><h3>Последние сообщения</h3><div class="admin-list">${(msgs||[]).map(m=>`<div class="admin-row"><span>${esc(m.body||'📷 Фото')}</span><button class="admin-delete" data-delete="${m.id}">Удалить</button></div>`).join('')}</div>`);document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const {error}=await state.supabase.from('messages').delete().eq('id',b.dataset.delete);if(error)return toast(error.message);b.closest('.admin-row').remove();toast('Сообщение удалено')})}

els.form.onsubmit=sendMessage;$('#chatSearch').oninput=e=>renderChats(e.target.value);$('#backButton').onclick=()=>els.app.classList.remove('chat-open');$('#attachButton').onclick=()=>els.photoInput.click();els.photoInput.onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>10_000_000)return toast('Максимум 10 МБ');state.photo=f;els.photoPreviewImage.src=URL.createObjectURL(f);els.photoPreviewSize.textContent=Math.round(f.size/1024)+' КБ';els.photoPreview.classList.remove('hidden')};$('#removePhotoButton').onclick=clearComposer;$('#settingsButton').onclick=profile;$('#addStoryButton').onclick=showAddStory;$('#chatMenuButton').onclick=newChat;$('#searchMessagesButton').onclick=()=>{const q=prompt('Найти сообщение');if(q){const m=state.messages.find(x=>(x.body||'').toLowerCase().includes(q.toLowerCase()));toast(m?'Найдено: '+m.body:'Не найдено')}};$('#notificationButton').onclick=async()=>{if(!('Notification'in window))return toast('Не поддерживается');toast(await Notification.requestPermission()==='granted'?'Уведомления разрешены':'Разрешение не выдано')};const em=['💗','💕','✨','😍','🥰','😂','🔥','🎀','💅','🌸','😭','😘'];$('#emojiPicker').innerHTML=em.map(x=>`<button type="button">${x}</button>`).join('');$('#emojiPicker').querySelectorAll('button').forEach(b=>b.onclick=()=>{els.input.value+=b.textContent;els.input.focus()});$('#emojiButton').onclick=()=>$('#emojiPicker').classList.toggle('hidden');els.input.oninput=()=>{els.input.style.height='auto';els.input.style.height=Math.min(els.input.scrollHeight,120)+'px'};
boot();

if ('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
